name: aryans_surfer
description: "Aryan's Surfer — a Flutter + Flame 3-lane endless runner."
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.11.0
  flame_forge2d: ^0.18.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
